### ISSUE TITLE
データストアに未定義のクラスのインスタンスを同時に複数保存しようとするとエラーになる

### ISSUE THREAD

**Issue by bkzen** [NIFCloud-mbaas/ncmb_js#191]
環境：
- Node.js バージョン：8.7.0
- ncmb_js バージョン：2.1.5

詳しい条件：
- リレーションオブジェクトを複数持っているオブジェクトを保存しようとした時
- 保存しようとしているオブジェクトのクラスが DataStore に定義されていない
- リレーション対象となるオブジェクトのクラスが DataStore に定義されていない

起こる現象：
- リレーション対象となるオブジェクトの1つ目だけが DataStore に登録される
- 以下のエラーが発生する

出力されたエラー内容は以下の通り：
> { Error: cannot POST /2013-09-01/classes/Food (409)
>     at Response.toError (/Users/pbi06455/node_modules/superagent/lib/node/response.js:106:13)
>     at Response.setStatusProperties (/Users/pbi06455/node_modules/superagent/lib/node/response.js:183:12)
>     at new Response (/Users/pbi06455/node_modules/superagent/lib/node/response.js:42:8)
>     at IncomingMessage.<anonymous> (/Users/pbi06455/node_modules/superagent/lib/node/index.js:918:22)
>     at emitNone (events.js:110:20)
>     at IncomingMessage.emit (events.js:207:7)
>     at endReadableNT (_stream_readable.js:1057:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
>   status: 409,
>   text: '{"code":"E409001","error":"Duplication Error"}',
>   method: 'POST',
>   path: '/2013-09-01/classes/Food' }

エラーが出たコードはドキュメントにある以下のソース：

```
var Food = ncmb.DataStore("food");
var food1 = new Food({name: "orange", type: "fruit"});
var food2 = new Food({name: "apple", type: "fruit"});
var relation = new ncmb.Relation();
relation.add(food1).add(food2);

var MainObj = ncmb.DataStore("MainObj");
var mainobj = new MainObj();
mainobj.set("foods", relation);

mainobj.save()
	.then(function(obj){
		console.log("done");
	})
	.catch(function(err){
		console.log(err);
	});
```

Monaca でテストした場合はエラーも起こらず、無事登録が行われた。

**Comment by bkzen** [comment]
この件について追記です。
Node.js のバージョンを推奨の v4.2.x で試しても同じでした。

また、コードを簡略化し、以下のコードを同一の条件(foodクラスが定義されていない状態)で実行した場合においても、同様のエラーコード `409001` が返ってきました。

```
    var Food = ncmb.DataStore("food");
    var food1 = new Food({name: "orange", type: "fruit"});
    var food2 = new Food({name: "apple", type: "fruit"});
    food1.save().then(console.log).catch(console.log);
    food2.save().then(console.log).catch(console.log);
```

どうやら **リレーションは関係なく** 、新規foodクラスを二つ作ろうとしてエラーが起きているようです。

monaca では上記のコードでもエラーは起きませんでしたが、帰ってきたデータの createDate が 200msほどずれていたので、試しに Node.js 側で上記のコードの `food2.save()` を `setTimeout()` で 100msほど遅延させて実行したところ、エラーが出ませんでした。

**Comment by bkzen** [comment]
調査の結果、REST API を並列に二つたたいても同様の現象が起きたので SDK のバグというわけではない事がわかりました。
以下の理由からドキュメント側の修正を行うことで対応することとして、この issue はクローズします。別途ドキュメント側で issue を作成します。
* エラーは最初の1度だけである。
* クラスを定義していれば起きないエラーである。
* クラスを未定義で運用する可能性が低い。
