### ISSUE TITLE
【会員管理】「!」を含むユーザー名・パスワードでのログインに失敗する

### ISSUE THREAD

**Issue by keikosanjo** [NIFCLOUD-mbaas/ncmb_js#232]
## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version)
    - v3.0.1
    - ※ v3.0.0では発生しませんでした
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
   - [ログイン](https://mbaas.nifcloud.com/doc/current/user/basic_usage_javascript.html#%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3) ＞// 2. Userインスタンスでログイン を、パスワードに「!」を含むユーザーで実施したところ、403エラーが返却されます。
```
var user = new ncmb.User({userName:"test", password:"test!"});
ncmb.User.login(user)
    .then(function(data){
      // ログイン後処理
    })
    .catch(function(err){
      // エラー処理
    });
```

- エラーメッセージ(Error messages)
```
{ Error: cannot GET /2013-09-01/login?userName=test&password=test%21 (403)
    at Response.toError (/ncmb_js-3.0.1/node_modules/superagent/lib/node/response.js:98:13)
    at ResponseBase._setStatusProperties (/ncmb_js-3.0.1/node_modules/superagent/lib/response-base.js:119:48)
    at new Response (/ncmb_js-3.0.1/node_modules/superagent/lib/node/response.js:44:8)
    at Request._emitResponse (/ncmb_js-3.0.1/node_modules/superagent/lib/node/index.js:904:18)
    at /ncmb_js-3.0.1/node_modules/superagent/lib/node/index.js:1100:42
    at IncomingMessage.<anonymous> (/ncmb_js-3.0.1/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 403,
  text:
   '{"code":"E403002","error":"Unauthorized operations for signature."}',
  method: 'GET',
  path: '/2013-09-01/login?userName=test&password=test%21',
  code: 'E403002',
  error: 'Unauthorized operations for signature.' }
```

**Comment by ncmbadmin** [comment]
本件はv3.0.2で対応いたしましたので、issueをクローズさせていただきます。
