### ISSUE TITLE
File.downloadがエラーとなります

### ISSUE THREAD

**Issue by inoueyuta** [NIFCLOUD-mbaas/ncmb_js#260]
## 不具合の概要(Description of bug)
- SDKのバージョン(SDK version):v3.1.0
- 不具合が発生した環境(Environment requirement): Cordova+Android, iOS
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
```
new NCMB(appKey, clientKey).File.download("sample.txt")
            .then(function(data) {
                console.log("File.download success data: " + data);
            })
            .catch(function(err) {
                console.log("error : " + err.message);
                console.log("error stack: " + err.stack);
            })
```
- 実行ログ
```
ncmb.min.js:36510 This is not supported in browser version of superagent
Request.agent @ ncmb.min.js:36510
(anonymous) @ ncmb.min.js:420
module.exports @ ncmb.min.js:420
File.download @ ncmb.min.js:394
(anonymous) @ index.js:54
index.js:59 error : Parser is unable to parse the response
index.js:60 error stack: Error: Parser is unable to parse the response
    at Request.<anonymous> (file:///android_asset/www/js/ncmb.min.js:36274:13)
    at Request.Emitter.emit (file:///android_asset/www/js/ncmb.min.js:11462:20)
    at XMLHttpRequest.xhr.onreadystatechange (file:///android_asset/www/js/ncmb.min.js:36606:10)
```

**Comment by inoueyuta** [comment]
v3.0.0では、本現象は発生しませんでした。

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございます。

順次、優先付けを行ったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend をどうぞよろしくお願いいたします。

**Comment by ncmbadmin** [comment]
お世話になっております。
本 issue の 改修が完了し v3.1.1 にてリリース済みです。
ご報告ありがとうございました。

改修済みのSDKは以下のリリースページにてご確認ください。
https://github.com/NIFCLOUD-mbaas/ncmb_js/releases

今後とも、mobile backend をどうぞよろしくお願いいたします。
